@startuml PrototypeDesignClassDiagram
'skinparam linetype ortho
'skinparam backgroundColor transparent
'skinparam handwritten true
'skinparam monochrome true
'left to right direction
skinparam sequenceMessageAlign direction
hide empty members
hide empty description
skinparam classAttributeIconSize 0
'skinparam style strictuml
skinparam groupInheritance 3

class Epub {
    <<Create>> fromCustom(controller: EpubParserController)
    <<Create>> fromBytes(bytes: List<int>)
    <<Create>> fromFile(file: File)
    <<Create>> fromExtracted(directory: Directory)
}

@enduml