image:
  file: .gitpod.Dockerfile

tasks:
  - before: |
      sudo mount -t tmpfs shm -osize=4096m /dev/shm
      dart pub get
      eval $(command gp env -e) # Load environment variables

      WAKATIME_PATH=~/.wakatime.cfg
      rm $WAKATIME_PATH
      touch $WAKATIME_PATH
      echo -n "${WAKATIME}" | base64 --decode  > $WAKATIME_PATH

      VSCODE_SETTINGS_PATH=$HOME/.config/Code/User/settings.json
      rm $VSCODE_SETTINGS_PATH
      mkdir $HOME/.config/Code
      mkdir $HOME/.config/Code/User
      touch $VSCODE_SETTINGS_PATH
      echo -n "${VSCODE_SETTINGS}" | base64 --decode  > $VSCODE_SETTINGS_PATH
  - init: |
      flutter upgrade
      dart --disable-analytics
      brew install git-flow
  - command: |
      wget -O "/home/gitpod/.cache/dart-data-class-generator-0.5.5_vsixhub.vsix" https://www.dropbox.com/s/1fx13fsjekiuwpk/dart-data-class-generator-0.5.5_vsixhub.vsix?dl=1
      code --install-extension /home/gitpod/.cache/dart-data-class-generator-0.5.5_vsixhub.vsix
      
      dart pub get

ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: ignore
    # flutter
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - dart-code.dart-code
    - wakatime.vscode-wakatime
